package by.epam.booking.service.user;

public enum UserInfoType {
    ALL,LOGIN,NAME,SURNAME,EMAIL,PASSWORD,ROLE,IS_ACTIVE,MONEY_BALANCE,
    BOOK,READING_PLAN_NAME, DELETE_BOOK,BOOK_NAME,DELETE_READING_PLAN;
}
